name: build
on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x' # SDK Version to use.
      - name: Create the package
        run: dotnet publish -c Release
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: LADXHD
          path: bin/Release/net8.0-windows/win-x64/publish/
